slam_reset_delay: 0.1
goals:
#  - name: "stefan_office_arrival"
#    x: -6.467
#    y: -6.790
#    rot: -2.359
#    reset_slam: true
#  - name: "stefan_office_start"
#    x: -6.475
#    y: -6.819
#    rot: 0.804
#    reset_slam: false
  - name: "florian_office_arrival"
    x: 12.780
    y: 12.198
    rot: 0.788
    reset_slam: true
#  - name: "florian_office_start"
#    x: 12.755
#    y: 12.224
#    rot: -2.349
#    reset_slam: false
